"""add_match_classification_flags

Revision ID: 47c89e525e9b
Revises: 693c8d84c06a
Create Date: 2025-12-26 16:05:33.448861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c89e525e9b'
down_revision: Union[str, Sequence[str], None] = '693c8d84c06a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('is_1v1', sa.Boolean(), nullable=True))
    op.add_column('matches', sa.Column('is_team_game', sa.Boolean(), nullable=True))
    op.add_column('matches', sa.Column('is_ranked', sa.Boolean(), nullable=True))
    op.add_column('matches', sa.Column('player_count', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('team_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_matches_is_1v1'), 'matches', ['is_1v1'], unique=False)
    op.create_index(op.f('ix_matches_is_ranked'), 'matches', ['is_ranked'], unique=False)
    op.create_index(op.f('ix_matches_is_team_game'), 'matches', ['is_team_game'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_is_team_game'), table_name='matches')
    op.drop_index(op.f('ix_matches_is_ranked'), table_name='matches')
    op.drop_index(op.f('ix_matches_is_1v1'), table_name='matches')
    op.drop_column('matches', 'team_count')
    op.drop_column('matches', 'player_count')
    op.drop_column('matches', 'is_ranked')
    op.drop_column('matches', 'is_team_game')
    op.drop_column('matches', 'is_1v1')
    # ### end Alembic commands ###
