"""add_unique_constraint_match_players

Revision ID: 693c8d84c06a
Revises: a794fa4c7aea
Create Date: 2025-12-26 15:54:56.336806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '693c8d84c06a'
down_revision: Union[str, Sequence[str], None] = 'a794fa4c7aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('match_players', schema=None) as batch_op:
        batch_op.alter_column('id',
                existing_type=sa.INTEGER(),
                nullable=False,
                autoincrement=True)
        batch_op.create_index('ix_match_players_match_team', ['match_id', 'team'], unique=False)
        batch_op.create_unique_constraint('uq_match_players_match_profile', ['match_id', 'aoe_profile_id'])

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('country',
                existing_type=sa.TEXT(),
                type_=sa.String(),
                existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('country',
                existing_type=sa.String(),
                type_=sa.TEXT(),
                existing_nullable=True)

    with op.batch_alter_table('match_players', schema=None) as batch_op:
        batch_op.drop_constraint('uq_match_players_match_profile', type_='unique')
        batch_op.drop_index('ix_match_players_match_team')
        batch_op.alter_column('id',
                existing_type=sa.INTEGER(),
                nullable=True,
                autoincrement=True)
    # ### end Alembic commands ###
