"""initial_schema

Revision ID: 82d6668195b9
Revises: 
Create Date: 2025-12-24 10:49:27.399426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d6668195b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('ladder_type', sa.String(), nullable=True),
    sa.Column('map_id', sa.Integer(), nullable=True),
    sa.Column('map_name', sa.String(), nullable=True),
    sa.Column('patch_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_matches_match_id'), 'matches', ['match_id'], unique=False)
    op.create_table('players',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('steam_id', sa.String(), nullable=True),
    sa.Column('aoe_profile_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('player_id'),
    sa.UniqueConstraint('steam_id')
    )
    op.create_index(op.f('ix_players_aoe_profile_id'), 'players', ['aoe_profile_id'], unique=True)
    op.create_table('match_players',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('aoe_profile_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.Column('civ_id', sa.Integer(), nullable=True),
    sa.Column('civ_name', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('won', sa.Boolean(), nullable=True),
    sa.Column('elo_before', sa.Integer(), nullable=True),
    sa.Column('elo_after', sa.Integer(), nullable=True),
    sa.Column('color', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aoe_profile_id'], ['players.aoe_profile_id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('match_id', 'aoe_profile_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_players')
    op.drop_index(op.f('ix_players_aoe_profile_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_matches_match_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
