"""add_aggregation_tables

Revision ID: a794fa4c7aea
Revises: 82d6668195b9
Create Date: 2025-12-24 10:51:29.901078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a794fa4c7aea'
down_revision: Union[str, Sequence[str], None] = '82d6668195b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agg_combat',
    sa.Column('player_a_id', sa.String(), nullable=False),
    sa.Column('player_b_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('total_games', sa.Integer(), nullable=True),
    sa.Column('wins_with', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_a_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['player_b_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_a_id', 'player_b_id', 'type')
    )
    op.create_table('agg_player_civ',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('civ_id', sa.Integer(), nullable=False),
    sa.Column('civ_name', sa.String(), nullable=True),
    sa.Column('total_games', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'civ_id')
    )
    op.create_table('agg_player_daily',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_games', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('elo_end', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'date')
    )
    op.create_table('agg_player_map',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('map_name', sa.String(), nullable=True),
    sa.Column('total_games', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'map_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agg_player_map')
    op.drop_table('agg_player_daily')
    op.drop_table('agg_player_civ')
    op.drop_table('agg_combat')
    # ### end Alembic commands ###
